name: Flutter CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - uses: actions/checkout@v3

      # Step 2: Set up Java
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin

      # Step 3: Set up Flutter
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'

      # Step 4: Run `flutter pub get` to install dependencies
      - run: flutter pub get
      - run: dart run flutter_launcher_icons
      
      # Step 5: Build the APK in release mode
      - run: flutter build apk --release

      # Step 6: Create a new GitHub release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: "release-${{ github.run_id }}"
          release_name: "Release - ${{ github.run_id }}"
          draft: false
          prerelease: false

      # Step 7: Upload the APK to the GitHub release
      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/app/outputs/flutter-apk/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive
